[package]
name = "rsubstitute"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "trait"
path = "bin/trait.rs"

[[bin]]
name = "trait_generics"
path = "bin/trait_generics.rs"

[[bin]]
name = "fn"
path = "bin/fn.rs"

[dependencies]
rsubstitute_core = { workspace = true }
rsubstitute_proc_macro = { workspace = true }